name: Run Reddit Scraper Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'  # runs daily at 6:30 AM UTC

jobs:
  run-reddit-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Reddit Scraper Script
        run: python notebooks/Reddit_Web_Scrape_Extract_Load_Raw.py
